// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 54f88da2564873f2 "AZZ", do not edit manually */
'use client';
import { className as className3, css as css3, fonts as fonts3, } from './chunk-VIPGA5M3.js';
import { className, className2, css, css2, fonts, fonts2, } from './chunk-AEXN245U.js';

// virtual:about-section
import { Fragment as Fragment3, } from 'react';
import { ContextProviders, } from 'unframer';

// https :https://framerusercontent.com/modules/U2Lz1OQzwBuSOtVe80AF/BPiNM9aYeypTZlUb96Cm/g0Z1UZXoH.js
import { jsx as _jsx2, jsxs as _jsxs, } from 'react/jsx-runtime';
import {
  addFonts as addFonts2,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx as cx2,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  RichText as RichText2,
  useComponentViewport as useComponentViewport2,
  useLocaleInfo as useLocaleInfo2,
  useVariantState as useVariantState2,
  withCSS as withCSS2,
  withFX,
  withOptimizedAppearEffect,
} from 'unframer';
import { LayoutGroup as LayoutGroup2, motion as motion2, MotionConfigContext as MotionConfigContext2, } from 'unframer';
import * as React2 from 'react';

// https :https://framerusercontent.com/modules/ibayJrQXN9PGxq5QXj3W/Wimpim7aXAkFv9QEt8fF/Hq8Cvmh7d.js
import { jsx as _jsx, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Link,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext, } from 'unframer';
import * as React from 'react';
var cycleOrder = ['lhb9VhlZ2', 'rhgFSi0AE',];
var serializationHash = 'framer-paqIk';
var variantClassNames = { lhb9VhlZ2: 'framer-v-z8188e', rhgFSi0AE: 'framer-v-v0uy36', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { delay: 0, duration: 0.3, ease: [0.12, 0.23, 0.5, 1,], type: 'tween', };
var Transition = ({ value, children, },) => {
  const config = React.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion.create(React.Fragment,);
var humanReadableVariantMap = { 'Variant 1': 'lhb9VhlZ2', Hover: 'rhgFSi0AE', };
var getProps = ({ height, id, width, ...props },) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    variant:
      (_ref =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref !== void 0
        ? _ref
        : 'lhb9VhlZ2',
  };
};
var createLayoutDependency = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className: className4, layoutId, variant, ...restProps } = getProps(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({ cycleOrder, defaultVariant: 'lhb9VhlZ2', variant, variantClassNames, },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const { activeVariantCallback, delay, } = useActiveVariantCallback(baseVariant,);
  const onMouseEnter1kjsgq2 = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true, },);
    setVariant('rhgFSi0AE',);
  },);
  const onMouseLeave1d3ez1f = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false, },);
    setVariant('lhb9VhlZ2',);
  },);
  const ref1 = React.useRef(null,);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx(Transition, {
        value: transition1,
        children: /* @__PURE__ */ _jsx(Link, {
          href: 'mailto:info@example.com',
          nodeId: 'lhb9VhlZ2',
          openInNewTab: true,
          children: /* @__PURE__ */ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(serializationHash, ...sharedStyleClassNames, 'framer-z8188e', className4, classNames,)} framer-17kttai`,
            'data-border': true,
            'data-framer-name': 'Variant 1',
            'data-highlight': true,
            layoutDependency,
            layoutId: 'lhb9VhlZ2',
            onMouseEnter: onMouseEnter1kjsgq2,
            ref: ref !== null && ref !== void 0 ? ref : ref1,
            style: {
              '--border-bottom-width': '1px',
              '--border-color': 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))',
              '--border-left-width': '1px',
              '--border-right-width': '1px',
              '--border-style': 'solid',
              '--border-top-width': '1px',
              backgroundColor: 'rgba(0, 0, 0, 0)',
              borderBottomLeftRadius: 5e3,
              borderBottomRightRadius: 5e3,
              borderTopLeftRadius: 5e3,
              borderTopRightRadius: 5e3,
              ...style,
            },
            variants: { rhgFSi0AE: { backgroundColor: 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))', }, },
            ...addPropertyOverrides(
              { rhgFSi0AE: { 'data-framer-name': 'Hover', onMouseLeave: onMouseLeave1d3ez1f, }, },
              baseVariant,
              gestureVariant,
            ),
            children: /* @__PURE__ */ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /* @__PURE__ */ _jsx(React.Fragment, {
                children: /* @__PURE__ */ _jsx(motion.p, {
                  style: {
                    '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                    '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                    '--framer-line-height': '16px',
                    '--framer-text-color': 'var(--extracted-r6o4lv, var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255)))',
                  },
                  children: 'Cotizar',
                },),
              },),
              className: 'framer-1dzwgkn',
              'data-framer-name': '123456789',
              fonts: ['GF;Jost-regular',],
              layoutDependency,
              layoutId: 'IackHZJL2',
              style: {
                '--extracted-r6o4lv': 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))',
                '--framer-paragraph-spacing': '0px',
              },
              variants: { rhgFSi0AE: { '--extracted-r6o4lv': 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', }, },
              verticalAlignment: 'top',
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  rhgFSi0AE: {
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.p, {
                        style: {
                          '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                          '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                          '--framer-line-height': '16px',
                          '--framer-text-color':
                            'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                        },
                        children: 'Cotizar',
                      },),
                    },),
                  },
                },
                baseVariant,
                gestureVariant,
              ),
            },),
          },),
        },),
      },),
    },),
  },);
},);
var css4 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-paqIk.framer-17kttai, .framer-paqIk .framer-17kttai { display: block; }',
  '.framer-paqIk.framer-z8188e { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 48px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 160px; }',
  '.framer-paqIk .framer-1dzwgkn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-paqIk.framer-z8188e { gap: 0px; } .framer-paqIk.framer-z8188e > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-paqIk.framer-z8188e > :first-child { margin-left: 0px; } .framer-paqIk.framer-z8188e > :last-child { margin-right: 0px; } }',
  '.framer-paqIk[data-border="true"]::after, .framer-paqIk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerHq8Cvmh7d = withCSS(Component, css4, 'framer-paqIk',);
var stdin_default = FramerHq8Cvmh7d;
FramerHq8Cvmh7d.displayName = 'Secondary Button White';
FramerHq8Cvmh7d.defaultProps = { height: 48, width: 160, };
addPropertyControls(FramerHq8Cvmh7d, {
  variant: { options: ['lhb9VhlZ2', 'rhgFSi0AE',], optionTitles: ['Variant 1', 'Hover',], title: 'Variant', type: ControlType.Enum, },
},);
addFonts(FramerHq8Cvmh7d, [{
  explicitInter: true,
  fonts: [{
    family: 'Jost',
    source: 'google',
    style: 'normal',
    url: 'https://fonts.gstatic.com/s/jost/v18/92zPtBhPNqw79Ij1E865zBUv7myjJQVDPokMmuHL.woff2',
    weight: '400',
  },],
},], { supportsExplicitInterCodegen: true, },);

// https :https://framerusercontent.com/modules/U2Lz1OQzwBuSOtVe80AF/BPiNM9aYeypTZlUb96Cm/g0Z1UZXoH.js
var SecondaryButtonWhiteFonts = getFonts(stdin_default,);
var ImageWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(Image,),);
var cycleOrder2 = ['SShCIfjM8', 'kWUrJuDav', 'bqTYGhPMj',];
var serializationHash2 = 'framer-OhbPc';
var variantClassNames2 = { bqTYGhPMj: 'framer-v-plt1bo', kWUrJuDav: 'framer-v-hz0soi', SShCIfjM8: 'framer-v-1awg0if', };
function addPropertyOverrides2(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition12 = { bounce: 0.2, delay: 0, duration: 0.4, type: 'spring', };
var transition2 = { damping: 30, delay: 0, mass: 1, stiffness: 400, type: 'spring', };
var animation = { opacity: 1, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition2, x: 0, y: 0, };
var animation1 = { opacity: 1e-3, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 0, };
var transition3 = { delay: 0, duration: 0.5, ease: [0.44, 0, 0.56, 1,], type: 'tween', };
var animation2 = { opacity: 1, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition3, x: 0, y: 0, };
var Transition2 = ({ value, children, },) => {
  const config = React2.useContext(MotionConfigContext2,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React2.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx2(MotionConfigContext2.Provider, { value: contextValue, children, },);
};
var Variants2 = motion2.create(React2.Fragment,);
var humanReadableVariantMap2 = { Desktop: 'SShCIfjM8', Phone: 'bqTYGhPMj', Tablet: 'kWUrJuDav', };
var getProps2 = ({ height, id, width, ...props },) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    variant:
      (_ref =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap2[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref !== void 0
        ? _ref
        : 'SShCIfjM8',
  };
};
var createLayoutDependency2 = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo2();
  const { style, className: className4, layoutId, variant, ...restProps } = getProps2(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState2({ cycleOrder: cycleOrder2, defaultVariant: 'SShCIfjM8', variant, variantClassNames: variantClassNames2, },);
  const layoutDependency = createLayoutDependency2(props, variants,);
  const ref1 = React2.useRef(null,);
  const isDisplayed = () => {
    if (baseVariant === 'bqTYGhPMj') return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === 'bqTYGhPMj') return true;
    return false;
  };
  const defaultLayoutId = React2.useId();
  const sharedStyleClassNames = [className, className2, className3,];
  const componentViewport = useComponentViewport2();
  return /* @__PURE__ */ _jsx2(LayoutGroup2, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx2(Variants2, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx2(Transition2, {
        value: transition12,
        children: /* @__PURE__ */ _jsx2(motion2.section, {
          ...restProps,
          ...gestureHandlers,
          className: cx2(serializationHash2, ...sharedStyleClassNames, 'framer-1awg0if', className4, classNames,),
          'data-framer-name': 'Desktop',
          layoutDependency,
          layoutId: 'SShCIfjM8',
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { backgroundColor: 'var(--token-faaffceb-79fe-4d6d-af24-1f64ffe1c6eb, rgb(22, 22, 18))', ...style, },
          ...addPropertyOverrides2(
            { bqTYGhPMj: { 'data-framer-name': 'Phone', }, kWUrJuDav: { 'data-framer-name': 'Tablet', }, },
            baseVariant,
            gestureVariant,
          ),
          children: /* @__PURE__ */ _jsxs(motion2.div, {
            className: 'framer-wwx9fr',
            'data-framer-name': 'About',
            layoutDependency,
            layoutId: 'ObzbKHuEd',
            children: [
              /* @__PURE__ */ _jsxs(motion2.div, {
                className: 'framer-59h11r',
                'data-framer-name': 'Content',
                layoutDependency,
                layoutId: 'FqK3fEzDm',
                children: [
                  /* @__PURE__ */ _jsxs(motion2.div, {
                    className: 'framer-56hf8j',
                    'data-framer-name': 'Preheading',
                    layoutDependency,
                    layoutId: 'FLFSexaFG',
                    children: [
                      /* @__PURE__ */ _jsx2(motion2.div, {
                        className: 'framer-anppnm',
                        'data-framer-name': 'Line',
                        layoutDependency,
                        layoutId: 'Fdr_eP4r6',
                        style: { backgroundColor: 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))', },
                      },),
                      /* @__PURE__ */ _jsx2(RichText2, {
                        __fromCanvasComponent: true,
                        children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                          children: /* @__PURE__ */ _jsx2(motion2.p, {
                            className: 'framer-styles-preset-1j02umx',
                            'data-styles-preset': 'b_p1W8xS2',
                            style: {
                              '--framer-text-color':
                                'var(--extracted-r6o4lv, var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255)))',
                            },
                            children: 'AZZ Cristal Soluciones',
                          },),
                        },),
                        className: 'framer-9yur26',
                        'data-framer-name': 'Furniture design studio',
                        fonts: ['Inter',],
                        layoutDependency,
                        layoutId: 'dgV_7rzIC',
                        style: {
                          '--extracted-r6o4lv': 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))',
                          '--framer-paragraph-spacing': '0px',
                        },
                        verticalAlignment: 'top',
                        withExternalLayout: true,
                      },),
                    ],
                  },),
                  /* @__PURE__ */ _jsxs(motion2.div, {
                    className: 'framer-opeo3p',
                    'data-framer-name': 'Grid',
                    layoutDependency,
                    layoutId: 'ZlHRNwp5K',
                    children: [
                      /* @__PURE__ */ _jsx2(RichText2, {
                        __fromCanvasComponent: true,
                        children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                          children: /* @__PURE__ */ _jsx2(motion2.h2, {
                            className: 'framer-styles-preset-1ss3aiu',
                            'data-styles-preset': 'in45SPA2Q',
                            style: {
                              '--framer-text-color':
                                'var(--extracted-1of0zx5, var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255)))',
                            },
                            children: 'Donde la elegancia se encuentra con el confort.',
                          },),
                        },),
                        className: 'framer-go4y5y',
                        'data-framer-name': 'Where Design Meets Comfort',
                        fonts: ['Inter',],
                        layoutDependency,
                        layoutId: 'mSTuqpOlJ',
                        style: {
                          '--extracted-1of0zx5': 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))',
                          '--framer-paragraph-spacing': '0px',
                        },
                        verticalAlignment: 'top',
                        withExternalLayout: true,
                      },),
                      /* @__PURE__ */ _jsx2(ComponentViewportProvider, {
                        height: 48,
                        y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 120 +
                          ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 1284) -
                                240 - 902) / 2 + 0 + 0) +
                          0 + 0 + 0 + 112 + 0 + 0,
                        ...addPropertyOverrides2(
                          {
                            bqTYGhPMj: {
                              y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 80 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      2368) - 160 - 828) / 2 + 0 + 0) +
                                0 + 0 + 0 + 112 + 0 + 96,
                            },
                            kWUrJuDav: {
                              y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 100 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      1364) - 200 - 982) / 2 + 0 + 0) +
                                0 + 0 + 0 + 112 + 0 + 96,
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                        children: /* @__PURE__ */ _jsx2(motion2.div, {
                          className: 'framer-1d8pdck-container',
                          layoutDependency,
                          layoutId: 'yJ6bxA0JZ-container',
                          children: /* @__PURE__ */ _jsx2(stdin_default, {
                            height: '100%',
                            id: 'yJ6bxA0JZ',
                            layoutId: 'yJ6bxA0JZ',
                            variant: 'lhb9VhlZ2',
                            width: '100%',
                          },),
                        },),
                      },),
                    ],
                  },),
                  /* @__PURE__ */ _jsxs(motion2.div, {
                    className: 'framer-1krouw8',
                    'data-framer-name': 'Paragraphs',
                    layoutDependency,
                    layoutId: 'yon8X5Car',
                    children: [
                      /* @__PURE__ */ _jsx2(RichText2, {
                        __fromCanvasComponent: true,
                        children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                          children: /* @__PURE__ */ _jsxs(motion2.p, {
                            className: 'framer-styles-preset-69qoq5',
                            'data-styles-preset': 'k1AZGjPAA',
                            style: {
                              '--framer-text-color':
                                'var(--extracted-r6o4lv, var(--token-9f6765da-f121-4764-acfb-40e5fdac6ff8, rgb(204, 204, 204)))',
                            },
                            children: [
                              'En ',
                              /* @__PURE__ */ _jsx2(motion2.strong, { children: 'AZZ Cristal', },),
                              ', creemos que la verdadera artesan\xEDa trasciende la est\xE9tica: se trata de crear piezas funcionales que enriquezcan la vida cotidiana. Cada creaci\xF3n es una perfecta armon\xEDa entre innovaci\xF3n y arte, dise\xF1ada para inspirar y transformar tus espacios. Desde la idea inicial hasta la instalaci\xF3n final, ponemos pasi\xF3n en cada detalle para garantizar que nuestras piezas sean tan \xFAnicas como los lugares que habitan.',
                            ],
                          },),
                        },),
                        className: 'framer-dtcwgz',
                        'data-framer-name':
                          'Furnique is a testament to bespoke craftsmanship, where every piece tells a story of innovation and elegance. Our passion lies in curating timeless furniture designs that resonate with discerning tastes. With meticulous attention to detail, we craft pieces that transform spaces into personalized sanctuaries of comfort and style.',
                        fonts: ['Inter', 'Inter-Bold',],
                        layoutDependency,
                        layoutId: 'Dg4XAPNHL',
                        style: {
                          '--extracted-r6o4lv': 'var(--token-9f6765da-f121-4764-acfb-40e5fdac6ff8, rgb(204, 204, 204))',
                          '--framer-paragraph-spacing': '0px',
                        },
                        verticalAlignment: 'top',
                        withExternalLayout: true,
                      },),
                      /* @__PURE__ */ _jsx2(RichText2, {
                        __fromCanvasComponent: true,
                        children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                          children: /* @__PURE__ */ _jsxs(motion2.p, {
                            className: 'framer-styles-preset-69qoq5',
                            'data-styles-preset': 'k1AZGjPAA',
                            style: {
                              '--framer-text-color':
                                'var(--extracted-r6o4lv, var(--token-9f6765da-f121-4764-acfb-40e5fdac6ff8, rgb(204, 204, 204)))',
                            },
                            children: [
                              'Entendemos que tus espacios son una extensi\xF3n de tu personalidad. Por eso, en ',
                              /* @__PURE__ */ _jsx2(motion2.strong, { children: 'AZZ Cristal', },),
                              ' trabajamos contigo para materializar tus ideas y convertirlas en realidad. Combinando dise\xF1o atemporal con funcionalidad moderna, entregamos soluciones personalizadas que equilibran belleza y practicidad. Cada proyecto refleja nuestro compromiso con la excelencia, transformando espacios comunes en expresiones extraordinarias de estilo y confort.',
                            ],
                          },),
                        },),
                        className: 'framer-1p4h7e0',
                        'data-framer-name':
                          'Furnique is a testament to bespoke craftsmanship, where every piece tells a story of innovation and elegance. Our passion lies in curating timeless furniture designs that resonate with discerning tastes. With meticulous attention to detail, we craft pieces that transform spaces into personalized sanctuaries of comfort and style.',
                        fonts: ['Inter', 'Inter-Bold',],
                        layoutDependency,
                        layoutId: 'Vkt4nfb_y',
                        style: {
                          '--extracted-r6o4lv': 'var(--token-9f6765da-f121-4764-acfb-40e5fdac6ff8, rgb(204, 204, 204))',
                          '--framer-paragraph-spacing': '0px',
                        },
                        verticalAlignment: 'top',
                        withExternalLayout: true,
                      },),
                    ],
                  },),
                ],
              },),
              /* @__PURE__ */ _jsxs(motion2.div, {
                className: 'framer-fw4on4',
                'data-framer-name': 'Images',
                layoutDependency,
                layoutId: 'Nx8lCKcmb',
                children: [
                  /* @__PURE__ */ _jsxs(ImageWithFXWithOptimizedAppearEffect, {
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    animate: animation,
                    background: {
                      alt: 'Luxury custom sofa and chairs',
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 120 +
                          ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 1284) -
                                240 - 902) / 2 + 0 + 0) +
                          0 + 402 + 0 + 0,
                      ),
                      pixelHeight: 720,
                      pixelWidth: 960,
                      positionX: 'center',
                      positionY: 'center',
                      sizes: `calc(max((min(${
                        (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                      }, 1120px) - 144px) / 3, 200px) * 2 + 32px)`,
                      src: 'https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg',
                      srcSet:
                        'https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg 960w',
                    },
                    className: 'framer-8txre3',
                    'data-framer-appear-id': '8txre3',
                    'data-framer-name': 'Image',
                    initial: animation1,
                    layoutDependency,
                    layoutId: 'inG0idjmX',
                    optimized: true,
                    ...addPropertyOverrides2(
                      {
                        bqTYGhPMj: {
                          background: {
                            alt: 'Luxury custom sofa and chairs',
                            loading: getLoadingLazyAtYPosition(
                              ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 80 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      2368) - 160 - 828) / 2 + 0 + 0) +
                                0 + 628 + 0 + 0,
                            ),
                            pixelHeight: 720,
                            pixelWidth: 960,
                            positionX: 'center',
                            positionY: 'center',
                            sizes: `max(min(${
                              (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                            }, 1120px) - 40px, 200px)`,
                            src: 'https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg',
                            srcSet:
                              'https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg 960w',
                          },
                        },
                        kWUrJuDav: {
                          background: {
                            alt: 'Luxury custom sofa and chairs',
                            loading: getLoadingLazyAtYPosition(
                              ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 100 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      1364) - 200 - 982) / 2 + 0 + 0) +
                                0 + 482 + 0 + 0,
                            ),
                            pixelHeight: 720,
                            pixelWidth: 960,
                            positionX: 'center',
                            positionY: 'center',
                            sizes: `calc(max((min(${
                              (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                            }, 1120px) - 144px) / 3, 200px) * 2 + 32px)`,
                            src: 'https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg',
                            srcSet:
                              'https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/UsS8UPOsnf4kBtx8t0L9gKXRvOg.jpg 960w',
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: [
                      isDisplayed() && /* @__PURE__ */ _jsx2(motion2.div, {
                        'aria-label': 'A triangular mask element for the hero image',
                        className: 'framer-1tfvb5e',
                        layoutDependency,
                        layoutId: 'Batv7Pd59',
                        style: {
                          backgroundColor: 'rgb(22, 22, 18)',
                          mask:
                            'url(\'https://framerusercontent.com/images/HI6SEj63Dw24htDHwIp9ylUM334.svg\') alpha no-repeat bottom left / contain add',
                          WebkitMask:
                            'url(\'https://framerusercontent.com/images/HI6SEj63Dw24htDHwIp9ylUM334.svg\') alpha no-repeat bottom left / contain add',
                        },
                      },),
                      isDisplayed1() && /* @__PURE__ */ _jsx2(motion2.div, {
                        className: 'framer-1wwyevz',
                        layoutDependency,
                        layoutId: 'hbCUcKfpU',
                        style: {
                          backgroundColor: 'rgb(22, 22, 18)',
                          mask:
                            'url(\'https://framerusercontent.com/images/TDBCxALZiGvdjXIWStpC4cDKOs.svg\') alpha no-repeat bottom left / contain add',
                          WebkitMask:
                            'url(\'https://framerusercontent.com/images/TDBCxALZiGvdjXIWStpC4cDKOs.svg\') alpha no-repeat bottom left / contain add',
                        },
                      },),
                    ],
                  },),
                  isDisplayed() && /* @__PURE__ */ _jsx2(ImageWithFXWithOptimizedAppearEffect, {
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    animate: animation2,
                    background: {
                      alt: 'Luxury custom chair',
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 120 +
                          ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 1284) -
                                240 - 902) / 2 + 0 + 0) +
                          0 + 402 + 0 + 0,
                      ),
                      pixelHeight: 768,
                      pixelWidth: 1024,
                      positionX: 'center',
                      positionY: 'center',
                      sizes: `max((min(${
                        (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                      }, 1120px) - 144px) / 3, 200px)`,
                      src: 'https://framerusercontent.com/images/QH9KCwtFHk1vIj79kT435UOCFI.jpeg',
                      srcSet:
                        'https://framerusercontent.com/images/QH9KCwtFHk1vIj79kT435UOCFI.jpeg?scale-down-to=512 512w,https://framerusercontent.com/images/QH9KCwtFHk1vIj79kT435UOCFI.jpeg 1024w',
                    },
                    className: 'framer-m57kpo',
                    'data-framer-appear-id': 'm57kpo',
                    'data-framer-name': 'Image',
                    initial: animation1,
                    layoutDependency,
                    layoutId: 'jfMOeAPR_',
                    optimized: true,
                    ...addPropertyOverrides2(
                      {
                        kWUrJuDav: {
                          background: {
                            alt: 'Luxury custom chair',
                            loading: getLoadingLazyAtYPosition(
                              ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 100 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      1364) - 200 - 982) / 2 + 0 + 0) +
                                0 + 482 + 0 + 0,
                            ),
                            pixelHeight: 768,
                            pixelWidth: 1024,
                            positionX: 'center',
                            positionY: 'center',
                            sizes: `max((min(${
                              (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                            }, 1120px) - 144px) / 3, 200px)`,
                            src: 'https://framerusercontent.com/images/QH9KCwtFHk1vIj79kT435UOCFI.jpeg',
                            srcSet:
                              'https://framerusercontent.com/images/QH9KCwtFHk1vIj79kT435UOCFI.jpeg?scale-down-to=512 512w,https://framerusercontent.com/images/QH9KCwtFHk1vIj79kT435UOCFI.jpeg 1024w',
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  },),
                  isDisplayed() && /* @__PURE__ */ _jsx2(ImageWithFXWithOptimizedAppearEffect, {
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    animate: animation2,
                    background: {
                      alt: 'Luxury custom sofa',
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 120 +
                          ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 1284) -
                                240 - 902) / 2 + 0 + 0) +
                          0 + 402 + 0 + 212.8,
                      ),
                      pixelHeight: 1200,
                      pixelWidth: 1200,
                      positionX: 'center',
                      positionY: 'center',
                      sizes: `max((min(${
                        (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                      }, 1120px) - 144px) / 3, 200px)`,
                      src: 'https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png',
                      srcSet:
                        'https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png?scale-down-to=512 512w,https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png 1200w',
                    },
                    className: 'framer-1h4yov4',
                    'data-framer-appear-id': '1h4yov4',
                    'data-framer-name': 'Image',
                    initial: animation1,
                    layoutDependency,
                    layoutId: 'm1Ud0EJtj',
                    optimized: true,
                    ...addPropertyOverrides2(
                      {
                        kWUrJuDav: {
                          background: {
                            alt: 'Luxury custom sofa',
                            loading: getLoadingLazyAtYPosition(
                              ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 100 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      1364) - 200 - 982) / 2 + 0 + 0) +
                                0 + 482 + 0 + 212.8,
                            ),
                            pixelHeight: 1200,
                            pixelWidth: 1200,
                            positionX: 'center',
                            positionY: 'center',
                            sizes: `max((min(${
                              (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                            }, 1120px) - 144px) / 3, 200px)`,
                            src: 'https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png',
                            srcSet:
                              'https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png?scale-down-to=512 512w,https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/aJ5LblWOZTeFyVgsn5lRZZ8AW94.png 1200w',
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: /* @__PURE__ */ _jsx2(motion2.div, {
                      'aria-label': 'A triangular mask element for the hero image',
                      className: 'framer-n67090',
                      layoutDependency,
                      layoutId: 'fravpnPuU',
                      style: {
                        backgroundColor: 'rgb(22, 22, 18)',
                        mask:
                          'url(\'https://framerusercontent.com/images/TDBCxALZiGvdjXIWStpC4cDKOs.svg\') alpha no-repeat bottom left / contain add',
                        WebkitMask:
                          'url(\'https://framerusercontent.com/images/TDBCxALZiGvdjXIWStpC4cDKOs.svg\') alpha no-repeat bottom left / contain add',
                      },
                    },),
                  },),
                ],
              },),
            ],
          },),
        },),
      },),
    },),
  },);
},);
var css5 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-OhbPc.framer-1v5qc2k, .framer-OhbPc .framer-1v5qc2k { display: block; }',
  '.framer-OhbPc.framer-1awg0if { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 120px 0px 120px 0px; position: relative; width: 1200px; }',
  '.framer-OhbPc .framer-wwx9fr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1120px; overflow: hidden; padding: 0px 40px 0px 40px; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-59h11r { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-56hf8j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-anppnm { flex: none; height: 2px; position: relative; width: 64px; }',
  '.framer-OhbPc .framer-9yur26, .framer-OhbPc .framer-dtcwgz, .framer-OhbPc .framer-1p4h7e0 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }',
  '.framer-OhbPc .framer-opeo3p { display: grid; flex: none; gap: 32px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(200px, 1fr)); grid-template-rows: repeat(1, minmax(0, 1fr)); height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-go4y5y { align-self: start; flex: none; height: 100%; justify-self: start; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-OhbPc .framer-1d8pdck-container { align-self: start; flex: none; height: auto; justify-self: start; position: relative; width: fit-content; }',
  '.framer-OhbPc .framer-1krouw8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-fw4on4 { display: grid; flex: none; gap: 32px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(3, minmax(200px, 1fr)); grid-template-rows: repeat(5, minmax(0, 1fr)); height: 500px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-8txre3 { align-self: start; flex: none; grid-column: auto / span 2; grid-row: auto / span 5; height: 100%; justify-self: start; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-1tfvb5e { bottom: 0px; flex: none; height: 100px; left: 0px; overflow: hidden; position: absolute; width: 80px; }',
  '.framer-OhbPc .framer-1wwyevz { aspect-ratio: 0.8 / 1; bottom: 0px; flex: none; height: var(--framer-aspect-ratio-supported, 75px); overflow: hidden; position: absolute; right: 0px; width: 60px; }',
  '.framer-OhbPc .framer-m57kpo { align-self: start; flex: none; grid-row: auto / span 2; height: 100%; justify-self: start; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-1h4yov4 { align-self: start; flex: none; grid-row: auto / span 3; height: 100%; justify-self: start; position: relative; width: 100%; }',
  '.framer-OhbPc .framer-n67090 { bottom: 0px; flex: none; height: 100px; overflow: hidden; position: absolute; right: 0px; width: 80px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-OhbPc.framer-1awg0if, .framer-OhbPc .framer-wwx9fr, .framer-OhbPc .framer-59h11r, .framer-OhbPc .framer-56hf8j, .framer-OhbPc .framer-1krouw8 { gap: 0px; } .framer-OhbPc.framer-1awg0if > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-OhbPc.framer-1awg0if > :first-child, .framer-OhbPc .framer-wwx9fr > :first-child, .framer-OhbPc .framer-59h11r > :first-child { margin-top: 0px; } .framer-OhbPc.framer-1awg0if > :last-child, .framer-OhbPc .framer-wwx9fr > :last-child, .framer-OhbPc .framer-59h11r > :last-child { margin-bottom: 0px; } .framer-OhbPc .framer-wwx9fr > * { margin: 0px; margin-bottom: calc(64px / 2); margin-top: calc(64px / 2); } .framer-OhbPc .framer-59h11r > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-OhbPc .framer-56hf8j > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-OhbPc .framer-56hf8j > :first-child, .framer-OhbPc .framer-1krouw8 > :first-child { margin-left: 0px; } .framer-OhbPc .framer-56hf8j > :last-child, .framer-OhbPc .framer-1krouw8 > :last-child { margin-right: 0px; } .framer-OhbPc .framer-1krouw8 > * { margin: 0px; margin-left: calc(32px / 2); margin-right: calc(32px / 2); } }',
  '.framer-OhbPc.framer-v-hz0soi.framer-1awg0if { padding: 100px 0px 100px 0px; width: 810px; }',
  '.framer-OhbPc.framer-v-hz0soi .framer-opeo3p { grid-auto-rows: min-content; grid-template-columns: repeat(1, minmax(200px, 1fr)); grid-template-rows: repeat(1, min-content); }',
  '.framer-OhbPc.framer-v-hz0soi .framer-go4y5y { height: auto; }',
  '.framer-OhbPc.framer-v-plt1bo.framer-1awg0if { padding: 80px 0px 80px 0px; width: 200px; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-wwx9fr { gap: 48px; padding: 0px 20px 0px 20px; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-anppnm { width: 48px; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-opeo3p { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; justify-content: flex-start; overflow: visible; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-go4y5y { align-self: unset; height: auto; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-1d8pdck-container { align-self: unset; width: auto; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-1krouw8 { flex-direction: column; gap: 24px; padding: 8px 0px 0px 0px; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-dtcwgz, .framer-OhbPc.framer-v-plt1bo .framer-1p4h7e0 { flex: none; width: 100%; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-fw4on4 { gap: 16px; grid-auto-rows: 200px; grid-template-columns: repeat(1, minmax(200px, 1fr)); grid-template-rows: repeat(1, 200px); height: min-content; }',
  '.framer-OhbPc.framer-v-plt1bo .framer-8txre3 { grid-column: unset; grid-row: unset; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-OhbPc.framer-v-plt1bo .framer-wwx9fr, .framer-OhbPc.framer-v-plt1bo .framer-opeo3p, .framer-OhbPc.framer-v-plt1bo .framer-1krouw8, .framer-OhbPc.framer-v-plt1bo .framer-fw4on4 { gap: 0px; } .framer-OhbPc.framer-v-plt1bo .framer-wwx9fr > * { margin: 0px; margin-bottom: calc(48px / 2); margin-top: calc(48px / 2); } .framer-OhbPc.framer-v-plt1bo .framer-wwx9fr > :first-child, .framer-OhbPc.framer-v-plt1bo .framer-opeo3p > :first-child, .framer-OhbPc.framer-v-plt1bo .framer-1krouw8 > :first-child { margin-top: 0px; } .framer-OhbPc.framer-v-plt1bo .framer-wwx9fr > :last-child, .framer-OhbPc.framer-v-plt1bo .framer-opeo3p > :last-child, .framer-OhbPc.framer-v-plt1bo .framer-1krouw8 > :last-child { margin-bottom: 0px; } .framer-OhbPc.framer-v-plt1bo .framer-opeo3p > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-OhbPc.framer-v-plt1bo .framer-1krouw8 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-OhbPc.framer-v-plt1bo .framer-fw4on4 > *, .framer-OhbPc.framer-v-plt1bo .framer-fw4on4 > :first-child, .framer-OhbPc.framer-v-plt1bo .framer-fw4on4 > :last-child { margin: 0px; } }',
  ...css,
  ...css2,
  ...css3,
];
var Framerg0Z1UZXoH = withCSS2(Component2, css5, 'framer-OhbPc',);
var stdin_default2 = Framerg0Z1UZXoH;
Framerg0Z1UZXoH.displayName = 'About Section';
Framerg0Z1UZXoH.defaultProps = { height: 1284, width: 1200, };
addPropertyControls2(Framerg0Z1UZXoH, {
  variant: {
    options: ['SShCIfjM8', 'kWUrJuDav', 'bqTYGhPMj',],
    optionTitles: ['Desktop', 'Tablet', 'Phone',],
    title: 'Variant',
    type: ControlType2.Enum,
  },
},);
addFonts2(Framerg0Z1UZXoH, [
  {
    explicitInter: true,
    fonts: [{
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
      url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
      url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+1F00-1FFF',
      url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0370-03FF',
      url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
      url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange:
        'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
      url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
      url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
      url: 'https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2',
      weight: '700',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
      url: 'https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2',
      weight: '700',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+1F00-1FFF',
      url: 'https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2',
      weight: '700',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0370-03FF',
      url: 'https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2',
      weight: '700',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
      url: 'https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2',
      weight: '700',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange:
        'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
      url: 'https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2',
      weight: '700',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
      url: 'https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2',
      weight: '700',
    },],
  },
  ...SecondaryButtonWhiteFonts,
  ...getFontsFromSharedStyle(fonts,),
  ...getFontsFromSharedStyle(fonts2,),
  ...getFontsFromSharedStyle(fonts3,),
], { supportsExplicitInterCodegen: true, },);

// virtual:about-section
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
var locales = [];
stdin_default2.Responsive = ({ locale, ...rest },) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: { 'D9LYPcRaL': { 'path': '/404', }, 'augiA20Il': { 'path': '/', }, },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default2,
          ...rest,
        },
      ),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
};
function ComponentWithRoot({ locale, ...rest },) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        'D9LYPcRaL': {
          'path': '/404',
        },
        'augiA20Il': {
          'path': '/',
        },
      },
      children: /* @__PURE__ */ jsx(stdin_default2, { ...rest, },),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
}
Object.assign(ComponentWithRoot, stdin_default2,);
export { ComponentWithRoot as default, };
