// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 54f88da2564873f2 "AZZ", do not edit manually */
'use client';

// virtual:experience-section
import { Fragment as Fragment2, } from 'react';
import { ContextProviders, } from 'unframer';

// https :https://framerusercontent.com/modules/jGcZQkEsVh4tXZ7VkTOy/3nsAcdQpz9i3gtuoa6Ue/HYWrfvC5y.js
import { jsx as _jsx, jsxs as _jsxs, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext, } from 'unframer';
import * as React from 'react';
var MotionSectionWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(motion.section,),);
var cycleOrder = ['nZxXZ0ZYx', 'FIFc4ymiu', 'wY5WbK7Vy',];
var serializationHash = 'framer-unw3w';
var variantClassNames = { FIFc4ymiu: 'framer-v-1su3jwn', nZxXZ0ZYx: 'framer-v-8gki88', wY5WbK7Vy: 'framer-v-fog5jh', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { delay: 0.5, duration: 0.3, ease: [0.44, 0, 0.56, 1,], type: 'tween', };
var animation = { opacity: 1, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition1, x: 0, y: 0, };
var animation1 = { opacity: 1e-3, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 0, };
var transition2 = { bounce: 0.2, delay: 0, duration: 0.4, type: 'spring', };
var Transition = ({ value, children, },) => {
  const config = React.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion.create(React.Fragment,);
var humanReadableVariantMap = { Desktop: 'nZxXZ0ZYx', Phone: 'wY5WbK7Vy', Tablet: 'FIFc4ymiu', };
var getProps = ({ height, id, width, ...props },) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    variant:
      (_ref =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref !== void 0
        ? _ref
        : 'nZxXZ0ZYx',
  };
};
var createLayoutDependency = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({ cycleOrder, defaultVariant: 'nZxXZ0ZYx', variant, variantClassNames, },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const ref1 = React.useRef(null,);
  const isDisplayed = () => {
    if (baseVariant === 'wY5WbK7Vy') return false;
    return true;
  };
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx(Transition, {
        value: transition2,
        children: /* @__PURE__ */ _jsxs(MotionSectionWithFXWithOptimizedAppearEffect, {
          ...restProps,
          ...gestureHandlers,
          __framer__presenceAnimate: animation,
          __framer__presenceInitial: animation1,
          __perspectiveFX: false,
          __smartComponentFX: true,
          __targetOpacity: 1,
          className: cx(serializationHash, ...sharedStyleClassNames, 'framer-8gki88', className, classNames,),
          'data-framer-appear-id': '8gki88',
          'data-framer-name': 'Desktop',
          layoutDependency,
          layoutId: 'nZxXZ0ZYx',
          optimized: true,
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style, },
          ...addPropertyOverrides(
            { FIFc4ymiu: { 'data-framer-name': 'Tablet', }, wY5WbK7Vy: { 'data-framer-name': 'Phone', }, },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /* @__PURE__ */ _jsxs(motion.div, {
              className: 'framer-mnoqsp',
              'data-framer-name': 'Item',
              layoutDependency,
              layoutId: 'fUbHnN5SA',
              children: [
                isDisplayed() && /* @__PURE__ */
                _jsx(motion.div, {
                  className: 'framer-8okc3v',
                  'data-framer-name': 'Line',
                  layoutDependency,
                  layoutId: 'eZ1GLXCoW',
                  style: { backgroundColor: 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', },
                },),
                /* @__PURE__ */ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /* @__PURE__ */ _jsx(React.Fragment, {
                    children: /* @__PURE__ */ _jsx(motion.p, { style: { '--framer-font-size': '33px', }, children: '+20', },),
                  },),
                  className: 'framer-1txkkw1',
                  fonts: ['Inter',],
                  layoutDependency,
                  layoutId: 'ky5L3VilH',
                  style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', },
                  verticalAlignment: 'top',
                  withExternalLayout: true,
                },),
                /* @__PURE__ */ _jsx(motion.div, {
                  className: 'framer-li4lps',
                  'data-framer-name': 'Content',
                  layoutDependency,
                  layoutId: 'fPgNyjV9o',
                  children: /* @__PURE__ */ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.p, {
                        style: {
                          '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                          '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                          '--framer-font-size': '20px',
                          '--framer-line-height': '20px',
                          '--framer-text-color':
                            'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                        },
                        children: 'A\xF1os de experiencia',
                      },),
                    },),
                    className: 'framer-ad3sgh',
                    'data-framer-name': 'Pieces of furniture',
                    fonts: ['GF;Jost-regular',],
                    layoutDependency,
                    layoutId: 'AKv2f6f6l',
                    style: {
                      '--extracted-r6o4lv': 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))',
                      '--framer-paragraph-spacing': '0px',
                    },
                    verticalAlignment: 'top',
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        wY5WbK7Vy: {
                          children: /* @__PURE__ */ _jsx(React.Fragment, {
                            children: /* @__PURE__ */ _jsx(motion.p, {
                              style: {
                                '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                                '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                                '--framer-line-height': '16px',
                                '--framer-text-color':
                                  'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                              },
                              children: 'A\xF1os de experiencia',
                            },),
                          },),
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  },),
                },),
              ],
            },),
            /* @__PURE__ */ _jsxs(motion.div, {
              className: 'framer-1rhag5p',
              'data-framer-name': 'Item',
              layoutDependency,
              layoutId: 'xzW7pr3R3',
              children: [
                isDisplayed() && /* @__PURE__ */
                _jsx(motion.div, {
                  className: 'framer-8xkkgl',
                  'data-framer-name': 'Line',
                  layoutDependency,
                  layoutId: 'VhhL8Tyq2',
                  style: { backgroundColor: 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', },
                },),
                /* @__PURE__ */ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /* @__PURE__ */ _jsx(React.Fragment, {
                    children: /* @__PURE__ */ _jsx(motion.p, { style: { '--framer-font-size': '33px', }, children: '+1,000', },),
                  },),
                  className: 'framer-55puks',
                  fonts: ['Inter',],
                  layoutDependency,
                  layoutId: 'Bk46_L3Gf',
                  style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', },
                  verticalAlignment: 'top',
                  withExternalLayout: true,
                },),
                /* @__PURE__ */ _jsx(motion.div, {
                  className: 'framer-5n8rgu',
                  'data-framer-name': 'Content',
                  layoutDependency,
                  layoutId: 'H11SsqCou',
                  children: /* @__PURE__ */ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.p, {
                        style: {
                          '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                          '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                          '--framer-font-size': '20px',
                          '--framer-line-height': '20px',
                          '--framer-text-color':
                            'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                        },
                        children: 'Clientes satisfechos',
                      },),
                    },),
                    className: 'framer-1d0fb5r',
                    'data-framer-name': 'Pieces of furniture',
                    fonts: ['GF;Jost-regular',],
                    layoutDependency,
                    layoutId: 'TLYwRPJ6A',
                    style: {
                      '--extracted-r6o4lv': 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))',
                      '--framer-paragraph-spacing': '0px',
                    },
                    verticalAlignment: 'top',
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        wY5WbK7Vy: {
                          children: /* @__PURE__ */ _jsx(React.Fragment, {
                            children: /* @__PURE__ */ _jsx(motion.p, {
                              style: {
                                '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                                '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                                '--framer-line-height': '16px',
                                '--framer-text-color':
                                  'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                              },
                              children: 'Clientes satisfechos',
                            },),
                          },),
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  },),
                },),
              ],
            },),
            /* @__PURE__ */ _jsxs(motion.div, {
              className: 'framer-1fjh1qk',
              'data-framer-name': 'Item',
              layoutDependency,
              layoutId: 'GS4sRWF3E',
              children: [
                isDisplayed() && /* @__PURE__ */
                _jsx(motion.div, {
                  className: 'framer-1k0klw6',
                  'data-framer-name': 'Line',
                  layoutDependency,
                  layoutId: 'cGOnX0Ufg',
                  style: { backgroundColor: 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', },
                },),
                /* @__PURE__ */ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /* @__PURE__ */ _jsx(React.Fragment, {
                    children: /* @__PURE__ */ _jsx(motion.p, { style: { '--framer-font-size': '33px', }, children: '+2,000', },),
                  },),
                  className: 'framer-1nnvv62',
                  fonts: ['Inter',],
                  layoutDependency,
                  layoutId: 'F0Z7IQbVl',
                  style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', },
                  verticalAlignment: 'top',
                  withExternalLayout: true,
                },),
                /* @__PURE__ */ _jsx(motion.div, {
                  className: 'framer-xexki1',
                  'data-framer-name': 'Content',
                  layoutDependency,
                  layoutId: 'ywsn0J1vx',
                  children: /* @__PURE__ */ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.p, {
                        style: {
                          '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                          '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                          '--framer-font-size': '20px',
                          '--framer-line-height': '20px',
                          '--framer-text-color':
                            'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                        },
                        children: 'Trabajos realizados',
                      },),
                    },),
                    className: 'framer-1tx3j9g',
                    'data-framer-name': 'Pieces of furniture',
                    fonts: ['GF;Jost-regular',],
                    layoutDependency,
                    layoutId: 'YJ394Oipw',
                    style: {
                      '--extracted-r6o4lv': 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))',
                      '--framer-paragraph-spacing': '0px',
                    },
                    verticalAlignment: 'top',
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        wY5WbK7Vy: {
                          children: /* @__PURE__ */ _jsx(React.Fragment, {
                            children: /* @__PURE__ */ _jsx(motion.p, {
                              style: {
                                '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                                '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                                '--framer-line-height': '16px',
                                '--framer-text-color':
                                  'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                              },
                              children: 'Trabajos realizados',
                            },),
                          },),
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  },),
                },),
              ],
            },),
          ],
        },),
      },),
    },),
  },);
},);
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-unw3w.framer-egg7ma, .framer-unw3w .framer-egg7ma { display: block; }',
  '.framer-unw3w.framer-8gki88 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: center; overflow: hidden; padding: 120px 40px 120px 40px; position: relative; width: 1200px; }',
  '.framer-unw3w .framer-mnoqsp, .framer-unw3w .framer-1rhag5p, .framer-unw3w .framer-1fjh1qk { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }',
  '.framer-unw3w .framer-8okc3v, .framer-unw3w .framer-8xkkgl, .framer-unw3w .framer-1k0klw6 { flex: none; height: 48px; position: relative; width: 2px; }',
  '.framer-unw3w .framer-1txkkw1, .framer-unw3w .framer-ad3sgh, .framer-unw3w .framer-55puks, .framer-unw3w .framer-1d0fb5r, .framer-unw3w .framer-1nnvv62, .framer-unw3w .framer-1tx3j9g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-unw3w .framer-li4lps, .framer-unw3w .framer-5n8rgu, .framer-unw3w .framer-xexki1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-unw3w.framer-8gki88, .framer-unw3w .framer-mnoqsp, .framer-unw3w .framer-li4lps, .framer-unw3w .framer-1rhag5p, .framer-unw3w .framer-5n8rgu, .framer-unw3w .framer-1fjh1qk, .framer-unw3w .framer-xexki1 { gap: 0px; } .framer-unw3w.framer-8gki88 > * { margin: 0px; margin-left: calc(120px / 2); margin-right: calc(120px / 2); } .framer-unw3w.framer-8gki88 > :first-child, .framer-unw3w .framer-mnoqsp > :first-child, .framer-unw3w .framer-1rhag5p > :first-child, .framer-unw3w .framer-1fjh1qk > :first-child { margin-left: 0px; } .framer-unw3w.framer-8gki88 > :last-child, .framer-unw3w .framer-mnoqsp > :last-child, .framer-unw3w .framer-1rhag5p > :last-child, .framer-unw3w .framer-1fjh1qk > :last-child { margin-right: 0px; } .framer-unw3w .framer-mnoqsp > *, .framer-unw3w .framer-1rhag5p > *, .framer-unw3w .framer-1fjh1qk > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-unw3w .framer-li4lps > *, .framer-unw3w .framer-5n8rgu > *, .framer-unw3w .framer-xexki1 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-unw3w .framer-li4lps > :first-child, .framer-unw3w .framer-5n8rgu > :first-child, .framer-unw3w .framer-xexki1 > :first-child { margin-top: 0px; } .framer-unw3w .framer-li4lps > :last-child, .framer-unw3w .framer-5n8rgu > :last-child, .framer-unw3w .framer-xexki1 > :last-child { margin-bottom: 0px; } }',
  '.framer-unw3w.framer-v-1su3jwn.framer-8gki88 { align-content: unset; align-items: unset; display: grid; gap: 32px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(200px, 1fr)); grid-template-rows: repeat(2, minmax(0, 1fr)); padding: 80px 40px 80px 40px; width: 810px; }',
  '.framer-unw3w.framer-v-1su3jwn .framer-mnoqsp, .framer-unw3w.framer-v-1su3jwn .framer-1rhag5p, .framer-unw3w.framer-v-1su3jwn .framer-1fjh1qk { align-self: start; height: 100%; justify-content: flex-start; justify-self: start; width: 100%; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-unw3w.framer-v-1su3jwn.framer-8gki88 { gap: 0px; } .framer-unw3w.framer-v-1su3jwn.framer-8gki88 > *, .framer-unw3w.framer-v-1su3jwn.framer-8gki88 > :first-child, .framer-unw3w.framer-v-1su3jwn.framer-8gki88 > :last-child { margin: 0px; } }',
  '.framer-unw3w.framer-v-fog5jh.framer-8gki88 { flex-direction: column; gap: 32px; justify-content: flex-start; padding: 80px 20px 80px 20px; width: 200px; }',
  '.framer-unw3w.framer-v-fog5jh .framer-mnoqsp, .framer-unw3w.framer-v-fog5jh .framer-1rhag5p, .framer-unw3w.framer-v-fog5jh .framer-1fjh1qk { flex-direction: column; justify-content: flex-start; }',
  '.framer-unw3w.framer-v-fog5jh .framer-ad3sgh { order: 0; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-unw3w.framer-v-fog5jh.framer-8gki88, .framer-unw3w.framer-v-fog5jh .framer-mnoqsp, .framer-unw3w.framer-v-fog5jh .framer-1rhag5p, .framer-unw3w.framer-v-fog5jh .framer-1fjh1qk { gap: 0px; } .framer-unw3w.framer-v-fog5jh.framer-8gki88 > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-unw3w.framer-v-fog5jh.framer-8gki88 > :first-child, .framer-unw3w.framer-v-fog5jh .framer-mnoqsp > :first-child, .framer-unw3w.framer-v-fog5jh .framer-1rhag5p > :first-child, .framer-unw3w.framer-v-fog5jh .framer-1fjh1qk > :first-child { margin-top: 0px; } .framer-unw3w.framer-v-fog5jh.framer-8gki88 > :last-child, .framer-unw3w.framer-v-fog5jh .framer-mnoqsp > :last-child, .framer-unw3w.framer-v-fog5jh .framer-1rhag5p > :last-child, .framer-unw3w.framer-v-fog5jh .framer-1fjh1qk > :last-child { margin-bottom: 0px; } .framer-unw3w.framer-v-fog5jh .framer-mnoqsp > *, .framer-unw3w.framer-v-fog5jh .framer-1rhag5p > *, .framer-unw3w.framer-v-fog5jh .framer-1fjh1qk > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }',
];
var FramerHYWrfvC5y = withCSS(Component, css, 'framer-unw3w',);
var stdin_default = FramerHYWrfvC5y;
FramerHYWrfvC5y.displayName = 'Experience Section';
FramerHYWrfvC5y.defaultProps = { height: 288, width: 1200, };
addPropertyControls(FramerHYWrfvC5y, {
  variant: {
    options: ['nZxXZ0ZYx', 'FIFc4ymiu', 'wY5WbK7Vy',],
    optionTitles: ['Desktop', 'Tablet', 'Phone',],
    title: 'Variant',
    type: ControlType.Enum,
  },
},);
addFonts(FramerHYWrfvC5y, [{
  explicitInter: true,
  fonts: [{
    family: 'Inter',
    source: 'framer',
    style: 'normal',
    unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
    url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
    weight: '400',
  }, {
    family: 'Inter',
    source: 'framer',
    style: 'normal',
    unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
    url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
    weight: '400',
  }, {
    family: 'Inter',
    source: 'framer',
    style: 'normal',
    unicodeRange: 'U+1F00-1FFF',
    url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
    weight: '400',
  }, {
    family: 'Inter',
    source: 'framer',
    style: 'normal',
    unicodeRange: 'U+0370-03FF',
    url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
    weight: '400',
  }, {
    family: 'Inter',
    source: 'framer',
    style: 'normal',
    unicodeRange: 'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
    url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
    weight: '400',
  }, {
    family: 'Inter',
    source: 'framer',
    style: 'normal',
    unicodeRange:
      'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
    url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
    weight: '400',
  }, {
    family: 'Inter',
    source: 'framer',
    style: 'normal',
    unicodeRange: 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
    url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
    weight: '400',
  }, {
    family: 'Jost',
    source: 'google',
    style: 'normal',
    url: 'https://fonts.gstatic.com/s/jost/v18/92zPtBhPNqw79Ij1E865zBUv7myjJQVDPokMmuHL.woff2',
    weight: '400',
  },],
},], { supportsExplicitInterCodegen: true, },);

// virtual:experience-section
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
var locales = [];
stdin_default.Responsive = ({ locale, ...rest },) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: { 'D9LYPcRaL': { 'path': '/404', }, 'augiA20Il': { 'path': '/', }, },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          ...rest,
        },
      ),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
};
function ComponentWithRoot({ locale, ...rest },) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        'D9LYPcRaL': {
          'path': '/404',
        },
        'augiA20Il': {
          'path': '/',
        },
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest, },),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
}
Object.assign(ComponentWithRoot, stdin_default,);
export { ComponentWithRoot as default, };
