// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 54f88da2564873f2 "AZZ", do not edit manually */
'use client';

// virtual:footer-button
import { Fragment as Fragment2, } from 'react';
import { ContextProviders, } from 'unframer';

// https :https://framerusercontent.com/modules/x7HJA1bjTyv95c8yCWGe/RMbauxXcrUzy1DAnh5QM/tljQuh9EC.js
import { jsx as _jsx, } from 'react/jsx-runtime';
import {
  addFonts,
  cx,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext, } from 'unframer';
import * as React from 'react';
var MotionAWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(motion.a,),);
var enabledGestures = { pE9Fv_2Tb: { hover: true, }, };
var serializationHash = 'framer-cPFQR';
var variantClassNames = { pE9Fv_2Tb: 'framer-v-1qs6zjv', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { delay: 0, duration: 0.5, ease: [0.44, 0, 0.56, 1,], type: 'tween', };
var animation = { opacity: 1, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition1, x: 0, y: 0, };
var animation1 = { opacity: 1e-3, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 0, };
var transition2 = { delay: 0, duration: 0.3, ease: [0.44, 0, 0.56, 1,], type: 'tween', };
var Transition = ({ value, children, },) => {
  const config = React.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion(React.Fragment,);
var getProps = ({ height, id, width, ...props },) => {
  return { ...props, };
};
var createLayoutDependency = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({ defaultVariant: 'pE9Fv_2Tb', enabledGestures, variant, variantClassNames, },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const ref1 = React.useRef(null,);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx(Transition, {
        value: transition2,
        children: /* @__PURE__ */ _jsx(Link, {
          href: 'mailto:info@example.com',
          openInNewTab: true,
          children: /* @__PURE__ */ _jsx(MotionAWithFXWithOptimizedAppearEffect, {
            ...restProps,
            ...gestureHandlers,
            __framer__presenceAnimate: animation,
            __framer__presenceInitial: animation1,
            __perspectiveFX: false,
            __smartComponentFX: true,
            __targetOpacity: 1,
            className: `${cx(serializationHash, ...sharedStyleClassNames, 'framer-1qs6zjv', className, classNames,)} framer-r9g6rp`,
            'data-border': true,
            'data-framer-appear-id': '1qs6zjv',
            'data-framer-name': 'Variant 1',
            layoutDependency,
            layoutId: 'pE9Fv_2Tb',
            optimized: true,
            ref: ref !== null && ref !== void 0 ? ref : ref1,
            style: {
              '--border-bottom-width': '1px',
              '--border-color': 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))',
              '--border-left-width': '1px',
              '--border-right-width': '1px',
              '--border-style': 'solid',
              '--border-top-width': '1px',
              backgroundColor: 'rgba(0, 0, 0, 0)',
              borderBottomLeftRadius: 5e3,
              borderBottomRightRadius: 5e3,
              borderTopLeftRadius: 5e3,
              borderTopRightRadius: 5e3,
              ...style,
            },
            variants: { 'pE9Fv_2Tb-hover': { backgroundColor: 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))', }, },
            ...addPropertyOverrides({ 'pE9Fv_2Tb-hover': { 'data-framer-name': void 0, }, }, baseVariant, gestureVariant,),
            children: /* @__PURE__ */ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /* @__PURE__ */ _jsx(React.Fragment, {
                children: /* @__PURE__ */ _jsx(motion.p, {
                  style: {
                    '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                    '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                    '--framer-font-size': '28px',
                    '--framer-line-height': '28px',
                    '--framer-text-color': 'var(--extracted-r6o4lv, var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255)))',
                  },
                  children: 'info@example.com',
                },),
              },),
              className: 'framer-xxhhmk',
              'data-framer-name': '123456789',
              fonts: ['GF;Jost-regular',],
              layoutDependency,
              layoutId: 'yIHoP26Rz',
              style: {
                '--extracted-r6o4lv': 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))',
                '--framer-paragraph-spacing': '0px',
              },
              variants: {
                'pE9Fv_2Tb-hover': { '--extracted-r6o4lv': 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', },
              },
              verticalAlignment: 'top',
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  'pE9Fv_2Tb-hover': {
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.p, {
                        style: {
                          '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                          '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                          '--framer-font-size': '28px',
                          '--framer-line-height': '28px',
                          '--framer-text-color':
                            'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                        },
                        children: 'info@example.com',
                      },),
                    },),
                  },
                },
                baseVariant,
                gestureVariant,
              ),
            },),
          },),
        },),
      },),
    },),
  },);
},);
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-cPFQR.framer-r9g6rp, .framer-cPFQR .framer-r9g6rp { display: block; }',
  '.framer-cPFQR.framer-1qs6zjv { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100px; justify-content: center; max-width: 1120px; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 1120px; }',
  '.framer-cPFQR .framer-xxhhmk { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cPFQR.framer-1qs6zjv { gap: 0px; } .framer-cPFQR.framer-1qs6zjv > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-cPFQR.framer-1qs6zjv > :first-child { margin-left: 0px; } .framer-cPFQR.framer-1qs6zjv > :last-child { margin-right: 0px; } }',
  '.framer-cPFQR[data-border="true"]::after, .framer-cPFQR [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramertljQuh9EC = withCSS(Component, css, 'framer-cPFQR',);
var stdin_default = FramertljQuh9EC;
FramertljQuh9EC.displayName = 'Footer Button';
FramertljQuh9EC.defaultProps = { height: 100, width: 1120, };
addFonts(FramertljQuh9EC, [{
  explicitInter: true,
  fonts: [{
    family: 'Jost',
    source: 'google',
    style: 'normal',
    url: 'https://fonts.gstatic.com/s/jost/v15/92zPtBhPNqw79Ij1E865zBUv7myjJQVDPokMmuHL.woff2',
    weight: '400',
  },],
},], { supportsExplicitInterCodegen: true, },);

// virtual:footer-button
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
var locales = [];
stdin_default.Responsive = ({ locale, ...rest },) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: { 'D9LYPcRaL': { 'path': '/404', }, 'augiA20Il': { 'path': '/', }, },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          ...rest,
        },
      ),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
};
function ComponentWithRoot({ locale, ...rest },) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        'D9LYPcRaL': {
          'path': '/404',
        },
        'augiA20Il': {
          'path': '/',
        },
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest, },),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
}
Object.assign(ComponentWithRoot, stdin_default,);
export { ComponentWithRoot as default, };
