// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 54f88da2564873f2 "AZZ", do not edit manually */
'use client';

// virtual:navigation-bar
import { Fragment as Fragment3, } from 'react';
import { ContextProviders, } from 'unframer';

// https :https://framerusercontent.com/modules/rSQZmXqXHfubijYn2vDz/lPIXJff40dAW8wAyN8zo/YyCilx55b.js
import { jsx as _jsx2, jsxs as _jsxs2, } from 'react/jsx-runtime';
import {
  addFonts as addFonts2,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx as cx2,
  getFonts,
  getFontsFromSharedStyle as getFontsFromSharedStyle2,
  Link as Link2,
  ResolveLinks,
  RichText as RichText2,
  useActiveVariantCallback as useActiveVariantCallback2,
  useComponentViewport as useComponentViewport2,
  useLocaleInfo as useLocaleInfo2,
  useRouter,
  useVariantState as useVariantState2,
  withCSS as withCSS2,
  withFX,
  withOptimizedAppearEffect,
} from 'unframer';
import { LayoutGroup as LayoutGroup2, motion as motion2, MotionConfigContext as MotionConfigContext2, } from 'unframer';
import * as React2 from 'react';

// https :https://framerusercontent.com/modules/riMXqEhjAGDxr4r0x7rF/VZ3TX363d4z29B8ZtTy0/I5UQY06IF.js
import { fontStore, } from 'unframer';
fontStore.loadFonts([],);
var fonts = [{ explicitInter: true, fonts: [], },];
var css = [
  '.framer-15F3N .framer-styles-preset-19ohdtx:not(.rich-text-wrapper), .framer-15F3N .framer-styles-preset-19ohdtx.rich-text-wrapper a { --framer-link-current-text-color: #111111; --framer-link-current-text-decoration: none; --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, #1c1b17); --framer-link-text-decoration: none; }',
];
var className = 'framer-15F3N';

// https :https://framerusercontent.com/modules/3NLy9WF96WZzCwVUJF9Y/yMIvurQXl2EFIYIIS4wB/VdxdAKoa0.js
import { jsx as _jsx, jsxs as _jsxs, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Link,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext, } from 'unframer';
import * as React from 'react';

// https :https://framerusercontent.com/modules/rNvAXYkWjAoOejWZSr6I/HqUrNIJ33O35zt46dYzC/I5UQY06IF.js
import { fontStore as fontStore2, } from 'unframer';
fontStore2.loadFonts([],);
var fonts2 = [{ explicitInter: true, fonts: [], },];
var css2 = [
  '.framer-15F3N .framer-styles-preset-19ohdtx:not(.rich-text-wrapper), .framer-15F3N .framer-styles-preset-19ohdtx.rich-text-wrapper a { --framer-link-current-text-color: #111111; --framer-link-current-text-decoration: none; --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, #1c1b17); --framer-link-text-decoration: none; }',
];
var className2 = 'framer-15F3N';

// https :https://framerusercontent.com/modules/3NLy9WF96WZzCwVUJF9Y/yMIvurQXl2EFIYIIS4wB/VdxdAKoa0.js
var cycleOrder = ['UJJQ8psmC', 'TemWsMrRQ',];
var serializationHash = 'framer-7Swkm';
var variantClassNames = { TemWsMrRQ: 'framer-v-ruroqo', UJJQ8psmC: 'framer-v-139t9t3', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: 'spring', };
var Transition = ({ value, children, },) => {
  const config = React.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion(React.Fragment,);
var humanReadableVariantMap = { Hover: 'TemWsMrRQ', Normal: 'UJJQ8psmC', };
var getProps = ({ height, id, link, navLinkName, width, ...props },) => {
  var _ref, _humanReadableVariantMap_props_variant, _ref1;
  return {
    ...props,
    n92Q_MiJy: (_ref = navLinkName !== null && navLinkName !== void 0 ? navLinkName : props.n92Q_MiJy) !== null && _ref !== void 0
      ? _ref
      : 'Nav Link',
    o4e9cqMzz: link !== null && link !== void 0 ? link : props.o4e9cqMzz,
    variant:
      (_ref1 =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref1 !== void 0
        ? _ref1
        : 'UJJQ8psmC',
  };
};
var createLayoutDependency = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className: className3, layoutId, variant, n92Q_MiJy, o4e9cqMzz, ...restProps } = getProps(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({ cycleOrder, defaultVariant: 'UJJQ8psmC', variant, variantClassNames, },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const { activeVariantCallback, delay, } = useActiveVariantCallback(baseVariant,);
  const onMouseEnter14d3t4w = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true, },);
    setVariant('TemWsMrRQ',);
  },);
  const onMouseLeave1sjsore = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false, },);
    setVariant('UJJQ8psmC',);
  },);
  const ref1 = React.useRef(null,);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [className2,];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx(Transition, {
        value: transition1,
        children: /* @__PURE__ */ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(serializationHash, ...sharedStyleClassNames, 'framer-139t9t3', className3, classNames,),
          'data-framer-name': 'Normal',
          'data-highlight': true,
          layoutDependency,
          layoutId: 'UJJQ8psmC',
          onMouseEnter: onMouseEnter14d3t4w,
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style, },
          ...addPropertyOverrides(
            { TemWsMrRQ: { 'data-framer-name': 'Hover', onMouseLeave: onMouseLeave1sjsore, }, },
            baseVariant,
            gestureVariant,
          ),
          children: [
            /* @__PURE__ */ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /* @__PURE__ */ _jsx(React.Fragment, {
                children: /* @__PURE__ */ _jsx(motion.p, {
                  style: {
                    '--font-selector': 'R0Y7Sm9zdC1yZWd1bGFy',
                    '--framer-font-family': '"Jost", "Jost Placeholder", sans-serif',
                    '--framer-line-height': '16px',
                    '--framer-text-alignment': 'center',
                    '--framer-text-color': 'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                  },
                  children: /* @__PURE__ */ _jsx(Link, {
                    href: o4e9cqMzz,
                    openInNewTab: false,
                    smoothScroll: true,
                    children: /* @__PURE__ */ _jsx(motion.a, {
                      className: 'framer-styles-preset-19ohdtx',
                      'data-styles-preset': 'I5UQY06IF',
                      children: 'Nav Link',
                    },),
                  },),
                },),
              },),
              className: 'framer-z7ive2',
              fonts: ['GF;Jost-regular',],
              layoutDependency,
              layoutId: 'H8uH35_SS',
              style: { '--extracted-r6o4lv': 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', },
              text: n92Q_MiJy,
              verticalAlignment: 'top',
              withExternalLayout: true,
            },),
            /* @__PURE__ */ _jsx(motion.div, {
              className: 'framer-jlbcut',
              layoutDependency,
              layoutId: 'YHvHekBX4',
              style: { backgroundColor: 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', opacity: 0, },
              variants: { TemWsMrRQ: { opacity: 1, }, },
            },),
          ],
        },),
      },),
    },),
  },);
},);
var css3 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-7Swkm.framer-1g3s0sw, .framer-7Swkm .framer-1g3s0sw { display: block; }',
  '.framer-7Swkm.framer-139t9t3 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: visible; padding: 4px 0px 0px 0px; position: relative; width: min-content; }',
  '.framer-7Swkm .framer-z7ive2 { --framer-custom-cursors: pointer; flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-7Swkm .framer-jlbcut { flex: none; height: 2px; overflow: visible; position: relative; width: 1px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-7Swkm.framer-139t9t3 { gap: 0px; } .framer-7Swkm.framer-139t9t3 > * { margin: 0px; margin-bottom: calc(2px / 2); margin-top: calc(2px / 2); } .framer-7Swkm.framer-139t9t3 > :first-child { margin-top: 0px; } .framer-7Swkm.framer-139t9t3 > :last-child { margin-bottom: 0px; } }',
  '.framer-7Swkm.framer-v-ruroqo .framer-jlbcut { align-self: stretch; width: auto; }',
  ...css2,
];
var FramerVdxdAKoa0 = withCSS(Component, css3, 'framer-7Swkm',);
var stdin_default = FramerVdxdAKoa0;
FramerVdxdAKoa0.displayName = 'Navbar Link';
FramerVdxdAKoa0.defaultProps = { height: 24, width: 59, };
addPropertyControls(FramerVdxdAKoa0, {
  variant: { options: ['UJJQ8psmC', 'TemWsMrRQ',], optionTitles: ['Normal', 'Hover',], title: 'Variant', type: ControlType.Enum, },
  n92Q_MiJy: { defaultValue: 'Nav Link', displayTextArea: false, title: 'Nav Link Name', type: ControlType.String, },
  o4e9cqMzz: { title: 'Link', type: ControlType.Link, },
},);
addFonts(FramerVdxdAKoa0, [{
  explicitInter: true,
  fonts: [{
    family: 'Jost',
    source: 'google',
    style: 'normal',
    url: 'https://fonts.gstatic.com/s/jost/v15/92zPtBhPNqw79Ij1E865zBUv7myjJQVDPokMmuHL.woff2',
    weight: '400',
  },],
}, ...getFontsFromSharedStyle(fonts2,),], { supportsExplicitInterCodegen: true, },);

// https :https://framerusercontent.com/modules/rSQZmXqXHfubijYn2vDz/lPIXJff40dAW8wAyN8zo/YyCilx55b.js
var NavbarLinkFonts = getFonts(stdin_default,);
var MotionNavWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(motion2.nav,),);
var cycleOrder2 = ['DrQGawCIG', 'shB3qavDz', 'GiXi2QuAm',];
var serializationHash2 = 'framer-cjrgf';
var variantClassNames2 = { DrQGawCIG: 'framer-v-bmckdm', GiXi2QuAm: 'framer-v-1vwf8r5', shB3qavDz: 'framer-v-84i228', };
function addPropertyOverrides2(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition12 = { delay: 0, duration: 0.5, ease: [0.12, 0.23, 0.5, 1,], type: 'tween', };
var animation = { opacity: 1, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition12, x: 0, y: 0, };
var animation1 = { opacity: 1e-3, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 0, };
var transition2 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: 'spring', };
var transition3 = { damping: 30, delay: 0, mass: 1, stiffness: 400, type: 'spring', };
var animation2 = { opacity: 0.6, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition3, };
var Transition2 = ({ value, children, },) => {
  const config = React2.useContext(MotionConfigContext2,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React2.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx2(MotionConfigContext2.Provider, { value: contextValue, children, },);
};
var Variants2 = motion2.create(React2.Fragment,);
var humanReadableVariantMap2 = { 'Phone Open': 'GiXi2QuAm', Desktop: 'DrQGawCIG', Phone: 'shB3qavDz', };
var getProps2 = ({ branName, easeOut300S, height, id, width, ...props },) => {
  var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
  return {
    ...props,
    FuIwQUBWq: (_ref = easeOut300S !== null && easeOut300S !== void 0 ? easeOut300S : props.FuIwQUBWq) !== null && _ref !== void 0
      ? _ref
      : { delay: 0, duration: 0.3, ease: [0.12, 0.23, 0.5, 1,], type: 'tween', },
    GsgKxkUdb: (_ref1 = branName !== null && branName !== void 0 ? branName : props.GsgKxkUdb) !== null && _ref1 !== void 0
      ? _ref1
      : 'AZZ Cristal',
    variant:
      (_ref2 =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap2[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref2 !== void 0
        ? _ref2
        : 'DrQGawCIG',
  };
};
var createLayoutDependency2 = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo2();
  const { style, className: className3, layoutId, variant, FuIwQUBWq, GsgKxkUdb, ...restProps } = getProps2(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState2({ cycleOrder: cycleOrder2, defaultVariant: 'DrQGawCIG', variant, variantClassNames: variantClassNames2, },);
  const layoutDependency = createLayoutDependency2(props, variants,);
  const { activeVariantCallback, delay, } = useActiveVariantCallback2(baseVariant,);
  const onTapk4rkxh = activeVariantCallback(async (...args) => {
    setVariant('GiXi2QuAm',);
  },);
  const onTap1pnisph = activeVariantCallback(async (...args) => {
    setVariant('shB3qavDz',);
  },);
  const ref1 = React2.useRef(null,);
  const isDisplayed = () => {
    if (['shB3qavDz', 'GiXi2QuAm',].includes(baseVariant,)) return true;
    return false;
  };
  const isDisplayed1 = () => {
    if (baseVariant === 'shB3qavDz') return false;
    return true;
  };
  const router = useRouter();
  const defaultLayoutId = React2.useId();
  const sharedStyleClassNames = [className,];
  const componentViewport = useComponentViewport2();
  return /* @__PURE__ */ _jsx2(LayoutGroup2, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx2(Variants2, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx2(Transition2, {
        value: transition2,
        ...addPropertyOverrides2({ GiXi2QuAm: { value: FuIwQUBWq, }, shB3qavDz: { value: FuIwQUBWq, }, }, baseVariant, gestureVariant,),
        children: /* @__PURE__ */ _jsx2(MotionNavWithFXWithOptimizedAppearEffect, {
          ...restProps,
          ...gestureHandlers,
          __framer__presenceAnimate: animation,
          __framer__presenceInitial: animation1,
          __perspectiveFX: false,
          __smartComponentFX: true,
          __targetOpacity: 1,
          className: cx2(serializationHash2, ...sharedStyleClassNames, 'framer-bmckdm', className3, classNames,),
          'data-border': true,
          'data-framer-appear-id': 'bmckdm',
          'data-framer-name': 'Desktop',
          layoutDependency,
          layoutId: 'DrQGawCIG',
          optimized: true,
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            '--border-bottom-width': '1px',
            '--border-color': 'var(--token-d9a23d8b-f0e3-436d-bd92-cf361755e5f8, rgb(153, 153, 153))',
            '--border-left-width': '0px',
            '--border-right-width': '0px',
            '--border-style': 'solid',
            '--border-top-width': '0px',
            backgroundColor: 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))',
            ...style,
          },
          ...addPropertyOverrides2(
            { GiXi2QuAm: { 'data-framer-name': 'Phone Open', }, shB3qavDz: { 'data-framer-name': 'Phone', }, },
            baseVariant,
            gestureVariant,
          ),
          children: /* @__PURE__ */ _jsxs2(motion2.div, {
            className: 'framer-1d7o1d3',
            'data-framer-name': 'Navbar Content',
            layoutDependency,
            layoutId: 'gifP_OGs1',
            children: [
              /* @__PURE__ */ _jsxs2(motion2.div, {
                className: 'framer-1eo2sqv',
                'data-framer-name': 'Logo',
                layoutDependency,
                layoutId: 'AP3KQcVGa',
                children: [
                  /* @__PURE__ */ _jsx2(RichText2, {
                    __fromCanvasComponent: true,
                    children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                      children: /* @__PURE__ */ _jsx2(motion2.p, {
                        style: {
                          '--font-selector': 'R0Y7TW9udGFnYS1yZWd1bGFy',
                          '--framer-font-family': '"Montaga", "Montaga Placeholder", serif',
                          '--framer-font-size': '24px',
                          '--framer-line-height': '24px',
                          '--framer-text-color':
                            'var(--extracted-r6o4lv, var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23)))',
                        },
                        children: /* @__PURE__ */ _jsx2(Link2, {
                          href: { webPageId: 'augiA20Il', },
                          nodeId: 'ceI6Hq0dP',
                          openInNewTab: false,
                          smoothScroll: false,
                          children: /* @__PURE__ */ _jsx2(motion2.a, {
                            className: 'framer-styles-preset-19ohdtx',
                            'data-styles-preset': 'I5UQY06IF',
                            children: 'Verdance',
                          },),
                        },),
                      },),
                    },),
                    className: 'framer-11khnxx',
                    fonts: ['GF;Montaga-regular',],
                    layoutDependency,
                    layoutId: 'ceI6Hq0dP',
                    style: { '--extracted-r6o4lv': 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))', },
                    text: GsgKxkUdb,
                    verticalAlignment: 'top',
                    whileHover: animation2,
                    withExternalLayout: true,
                  },),
                  isDisplayed() && /* @__PURE__ */ _jsxs2(motion2.div, {
                    className: 'framer-1uyuyj',
                    'data-framer-name': 'Nav Icon',
                    layoutDependency,
                    layoutId: 'htoEgWdRL',
                    style: { backgroundColor: 'var(--token-c56d8574-58b3-4dc7-b6e2-bd40137097b4, rgb(255, 255, 255))', },
                    variants: { GiXi2QuAm: { backgroundColor: 'rgba(0, 0, 0, 0)', }, shB3qavDz: { backgroundColor: 'rgba(0, 0, 0, 0)', }, },
                    ...addPropertyOverrides2(
                      {
                        GiXi2QuAm: { 'data-highlight': true, onTap: onTap1pnisph, },
                        shB3qavDz: { 'data-highlight': true, onTap: onTapk4rkxh, },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                    children: [
                      /* @__PURE__ */ _jsx2(motion2.div, {
                        className: 'framer-1og28d2',
                        'data-framer-name': 'Bottom',
                        layoutDependency,
                        layoutId: 'sJ0Jep_JA',
                        style: {
                          backgroundColor: 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))',
                          borderBottomLeftRadius: 10,
                          borderBottomRightRadius: 10,
                          borderTopLeftRadius: 10,
                          borderTopRightRadius: 10,
                          rotate: 0,
                        },
                        variants: { GiXi2QuAm: { rotate: 45, }, },
                      },),
                      /* @__PURE__ */ _jsx2(motion2.div, {
                        className: 'framer-uuiin9',
                        'data-framer-name': 'Middle',
                        layoutDependency,
                        layoutId: 'E65y5b4Pl',
                        style: {
                          backgroundColor: 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))',
                          borderBottomLeftRadius: 10,
                          borderBottomRightRadius: 10,
                          borderTopLeftRadius: 10,
                          borderTopRightRadius: 10,
                          opacity: 1,
                        },
                        variants: { GiXi2QuAm: { opacity: 0, }, },
                      },),
                      /* @__PURE__ */ _jsx2(motion2.div, {
                        className: 'framer-rvk9hq',
                        'data-framer-name': 'Top',
                        layoutDependency,
                        layoutId: 'ToU1JFCmP',
                        style: {
                          backgroundColor: 'var(--token-e206300f-f993-4343-a0ac-348ae117b5b1, rgb(28, 27, 23))',
                          borderBottomLeftRadius: 10,
                          borderBottomRightRadius: 10,
                          borderTopLeftRadius: 10,
                          borderTopRightRadius: 10,
                          rotate: 0,
                        },
                        variants: { GiXi2QuAm: { rotate: -45, }, },
                      },),
                    ],
                  },),
                ],
              },),
              isDisplayed1() && /* @__PURE__ */ _jsxs2(motion2.div, {
                className: 'framer-10rliob',
                'data-framer-name': 'Nav Links',
                layoutDependency,
                layoutId: 'ciIRJapQk',
                children: [
                  /* @__PURE__ */ _jsx2(ResolveLinks, {
                    links: [{ href: { hash: ':KZzizB5oP', webPageId: 'augiA20Il', }, implicitPathVariables: void 0, }, {
                      href: { hash: ':KZzizB5oP', webPageId: 'augiA20Il', },
                      implicitPathVariables: void 0,
                    },],
                    children: (resolvedLinks,) =>
                      /* @__PURE__ */ _jsx2(ComponentViewportProvider, {
                        height: 24,
                        y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 0 +
                          ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 90) - 0 -
                                24) / 2 + 0 + 0) +
                          0 + 0,
                        ...addPropertyOverrides2(
                          {
                            GiXi2QuAm: {
                              y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 0 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      249) - 0 - 248.8) / 2 + 0 + 0) +
                                24 + 32 + 32 + 0,
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                        children: /* @__PURE__ */ _jsx2(motion2.div, {
                          className: 'framer-z7baiy-container',
                          layoutDependency,
                          layoutId: 'OOZujuQw6-container',
                          children: /* @__PURE__ */ _jsx2(stdin_default, {
                            height: '100%',
                            id: 'OOZujuQw6',
                            layoutId: 'OOZujuQw6',
                            n92Q_MiJy: 'Nosotros',
                            o4e9cqMzz: resolvedLinks[0],
                            variant: 'UJJQ8psmC',
                            width: '100%',
                            ...addPropertyOverrides2({ GiXi2QuAm: { o4e9cqMzz: resolvedLinks[1], }, }, baseVariant, gestureVariant,),
                          },),
                        },),
                      },),
                  },),
                  /* @__PURE__ */ _jsx2(ResolveLinks, {
                    links: [{ href: { hash: ':ns_aEa1pA', webPageId: 'augiA20Il', }, implicitPathVariables: void 0, }, {
                      href: { hash: ':ns_aEa1pA', webPageId: 'augiA20Il', },
                      implicitPathVariables: void 0,
                    },],
                    children: (resolvedLinks1,) =>
                      /* @__PURE__ */ _jsx2(ComponentViewportProvider, {
                        height: 24,
                        y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 0 +
                          ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 90) - 0 -
                                24) / 2 + 0 + 0) +
                          0 + 0,
                        ...addPropertyOverrides2(
                          {
                            GiXi2QuAm: {
                              y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 0 +
                                ((((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) ||
                                      249) - 0 - 248.8) / 2 + 0 + 0) +
                                24 + 32 + 32 + 56,
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        ),
                        children: /* @__PURE__ */ _jsx2(motion2.div, {
                          className: 'framer-dnl02t-container',
                          layoutDependency,
                          layoutId: 'eOExhAYLl-container',
                          children: /* @__PURE__ */ _jsx2(stdin_default, {
                            height: '100%',
                            id: 'eOExhAYLl',
                            layoutId: 'eOExhAYLl',
                            n92Q_MiJy: 'Servicios',
                            o4e9cqMzz: resolvedLinks1[0],
                            variant: 'UJJQ8psmC',
                            width: '100%',
                            ...addPropertyOverrides2({ GiXi2QuAm: { o4e9cqMzz: resolvedLinks1[1], }, }, baseVariant, gestureVariant,),
                          },),
                        },),
                      },),
                  },),
                ],
              },),
              /* @__PURE__ */ _jsx2(RichText2, {
                __fromCanvasComponent: true,
                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                    style: { '--framer-font-size': '14px', },
                    children: '.            .                 ',
                  },),
                },),
                className: 'framer-myuh8i',
                fonts: ['Inter',],
                layoutDependency,
                layoutId: 'AztnIa8I_',
                style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', opacity: 0, },
                verticalAlignment: 'top',
                withExternalLayout: true,
              },),
            ],
          },),
        },),
      },),
    },),
  },);
},);
var css4 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-cjrgf.framer-sujhas, .framer-cjrgf .framer-sujhas { display: block; }',
  '.framer-cjrgf.framer-bmckdm { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 90px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }',
  '.framer-cjrgf .framer-1d7o1d3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1200px; overflow: hidden; padding: 0px 40px 0px 40px; position: relative; width: 100%; }',
  '.framer-cjrgf .framer-1eo2sqv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }',
  '.framer-cjrgf .framer-11khnxx { --framer-custom-cursors: pointer; flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-cjrgf .framer-1uyuyj { flex: none; height: 32px; overflow: hidden; position: relative; width: 32px; }',
  '.framer-cjrgf .framer-1og28d2 { bottom: 7px; flex: none; height: 2px; left: calc(50.00000000000002% - 22px / 2); overflow: hidden; position: absolute; width: 22px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-cjrgf .framer-uuiin9 { flex: none; height: 2px; left: calc(50.00000000000002% - 22px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 22px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-cjrgf .framer-rvk9hq { flex: none; height: 2px; left: calc(50.00000000000002% - 22px / 2); overflow: hidden; position: absolute; top: 7px; width: 22px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-cjrgf .framer-10rliob { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }',
  '.framer-cjrgf .framer-z7baiy-container, .framer-cjrgf .framer-dnl02t-container { flex: none; height: auto; position: relative; width: auto; }',
  '.framer-cjrgf .framer-myuh8i { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cjrgf.framer-bmckdm, .framer-cjrgf .framer-1eo2sqv, .framer-cjrgf .framer-10rliob { gap: 0px; } .framer-cjrgf.framer-bmckdm > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-cjrgf.framer-bmckdm > :first-child { margin-top: 0px; } .framer-cjrgf.framer-bmckdm > :last-child { margin-bottom: 0px; } .framer-cjrgf .framer-1eo2sqv > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-cjrgf .framer-1eo2sqv > :first-child, .framer-cjrgf .framer-10rliob > :first-child { margin-left: 0px; } .framer-cjrgf .framer-1eo2sqv > :last-child, .framer-cjrgf .framer-10rliob > :last-child { margin-right: 0px; } .framer-cjrgf .framer-10rliob > * { margin: 0px; margin-left: calc(32px / 2); margin-right: calc(32px / 2); } }',
  '.framer-cjrgf.framer-v-84i228.framer-bmckdm, .framer-cjrgf.framer-v-1vwf8r5.framer-bmckdm { height: min-content; width: 390px; }',
  '.framer-cjrgf.framer-v-84i228 .framer-1d7o1d3 { padding: 24px 20px 24px 20px; }',
  '.framer-cjrgf.framer-v-84i228 .framer-1eo2sqv { flex: 1 0 0px; gap: unset; justify-content: space-evenly; width: 1px; }',
  '.framer-cjrgf.framer-v-84i228 .framer-1uyuyj, .framer-cjrgf.framer-v-1vwf8r5 .framer-1uyuyj { cursor: pointer; }',
  '.framer-cjrgf.framer-v-84i228 .framer-myuh8i { white-space: pre-wrap; width: 7px; word-break: break-word; word-wrap: break-word; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cjrgf.framer-v-84i228 .framer-1eo2sqv { gap: 0px; } .framer-cjrgf.framer-v-84i228 .framer-1eo2sqv > *, .framer-cjrgf.framer-v-84i228 .framer-1eo2sqv > :first-child, .framer-cjrgf.framer-v-84i228 .framer-1eo2sqv > :last-child { margin: 0px; } }',
  '.framer-cjrgf.framer-v-1vwf8r5 .framer-1d7o1d3 { flex-direction: column; padding: 24px 20px 32px 20px; }',
  '.framer-cjrgf.framer-v-1vwf8r5 .framer-1eo2sqv { gap: unset; justify-content: space-around; width: 100%; }',
  '.framer-cjrgf.framer-v-1vwf8r5 .framer-1og28d2 { bottom: unset; top: calc(50.00000000000002% - 2px / 2); }',
  '.framer-cjrgf.framer-v-1vwf8r5 .framer-uuiin9 { left: calc(50.00000000000002% - 2px / 2); width: 2px; }',
  '.framer-cjrgf.framer-v-1vwf8r5 .framer-rvk9hq { top: calc(50.00000000000002% - 2px / 2); }',
  '.framer-cjrgf.framer-v-1vwf8r5 .framer-10rliob { flex-direction: column; padding: 32px 0px 32px 0px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cjrgf.framer-v-1vwf8r5 .framer-1d7o1d3, .framer-cjrgf.framer-v-1vwf8r5 .framer-1eo2sqv, .framer-cjrgf.framer-v-1vwf8r5 .framer-10rliob { gap: 0px; } .framer-cjrgf.framer-v-1vwf8r5 .framer-1d7o1d3 > *, .framer-cjrgf.framer-v-1vwf8r5 .framer-1d7o1d3 > :first-child, .framer-cjrgf.framer-v-1vwf8r5 .framer-1d7o1d3 > :last-child, .framer-cjrgf.framer-v-1vwf8r5 .framer-1eo2sqv > *, .framer-cjrgf.framer-v-1vwf8r5 .framer-1eo2sqv > :first-child, .framer-cjrgf.framer-v-1vwf8r5 .framer-1eo2sqv > :last-child { margin: 0px; } .framer-cjrgf.framer-v-1vwf8r5 .framer-10rliob > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-cjrgf.framer-v-1vwf8r5 .framer-10rliob > :first-child { margin-top: 0px; } .framer-cjrgf.framer-v-1vwf8r5 .framer-10rliob > :last-child { margin-bottom: 0px; } }',
  ...css,
  '.framer-cjrgf[data-border="true"]::after, .framer-cjrgf [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerYyCilx55b = withCSS2(Component2, css4, 'framer-cjrgf',);
var stdin_default2 = FramerYyCilx55b;
FramerYyCilx55b.displayName = 'Navigation Bar';
FramerYyCilx55b.defaultProps = { height: 90, width: 1200, };
addPropertyControls2(FramerYyCilx55b, {
  variant: {
    options: ['DrQGawCIG', 'shB3qavDz', 'GiXi2QuAm',],
    optionTitles: ['Desktop', 'Phone', 'Phone Open',],
    title: 'Variant',
    type: ControlType2.Enum,
  },
  FuIwQUBWq: {
    defaultValue: { delay: 0, duration: 0.3, ease: [0.12, 0.23, 0.5, 1,], type: 'tween', },
    title: 'Ease Out 300s',
    type: ControlType2.Transition,
  },
  GsgKxkUdb: { defaultValue: 'AZZ Cristal', description: '', displayTextArea: false, title: 'branName', type: ControlType2.String, },
},);
addFonts2(FramerYyCilx55b, [
  {
    explicitInter: true,
    fonts: [{
      family: 'Montaga',
      source: 'google',
      style: 'normal',
      url: 'https://fonts.gstatic.com/s/montaga/v13/H4cnBX2Ml8rCkEO_0gMQ7LO5mqc.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
      url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
      url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+1F00-1FFF',
      url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0370-03FF',
      url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
      url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange:
        'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
      url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
      url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
      weight: '400',
    },],
  },
  ...NavbarLinkFonts,
  ...getFontsFromSharedStyle2(fonts,),
], { supportsExplicitInterCodegen: true, },);

// virtual:navigation-bar
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
var locales = [];
stdin_default2.Responsive = ({ locale, ...rest },) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: { 'D9LYPcRaL': { 'path': '/404', }, 'augiA20Il': { 'path': '/', }, },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default2,
          ...rest,
        },
      ),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
};
function ComponentWithRoot({ locale, ...rest },) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        'D9LYPcRaL': {
          'path': '/404',
        },
        'augiA20Il': {
          'path': '/',
        },
      },
      children: /* @__PURE__ */ jsx(stdin_default2, { ...rest, },),
      framerSiteId: '54f88da2564873f26d228db5e9005ef1a3394f7a04639befb90ade3f8b4a13d5',
      locale,
      locales,
    },
  );
}
Object.assign(ComponentWithRoot, stdin_default2,);
export { ComponentWithRoot as default, };
